# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.tddui
canonical: https://interop.esante.gouv.fr/ig/fhir/tddui # the last part of canonical and id must be the same
name: TDDUI
title: Médicosocial - Transfert de données DUI
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 1.0.1 # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    hl7.fhir.fr.core: 1.1.0
    ans.fr.nos: 1.1.0

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    sfe.md:
        title : Spécifications fonctionnelles
        sfe_cadre_juridique.md:
            title : Cadre juridique et orientations organisationnelles
        sfe_organisation_contexte_metier.md:
            title : Organisation du contexte métier
        sfe_definition_processus.md:
            title : Définition des processus collaboratifs
        sfe_modelisation_contenu.md :
            title : Modélisation du contenu du DUI
    contenu_dossier.md: 
        title : Contenu du dossier
        contenu_dossier_contexte.md:
            title : Contexte
        contenu_dossier_structure_cda.md:
            title: Structure générale du document CDA
        contenu_dossier_entete_cda.md:
            title: Entête du document CDA
        contenu_dossier_corps_cda.md: 
            title: Corps du document CDA
    description_flux.md:
        title : Description des flux
        description_flux_synthese.md:
            title: Synthèse des flux
        description_flux_1_ajout_doc.md:
            title: Flux 1 - Ajout d'un document
        description_flux_2_ajout_lot_doc.md:
            title: Flux 2 - Ajout d'un lot de documents
        description_flux_3_maj_doc.md:
            title: Flux 3 - Mise à jour d'un document
    ressources_conformite.md:
        title : Ressources de conformité
        ressources_cda.md:
            title: Ressources CDA
        artifacts.html:
            title: Ressources FHIR
    annexes.md:
        title: Annexes
        acronymes.md:
            title: Acronymes
        documents_reference.md:
            title: Documents de référence

menu:
    Accueil: index.html
    Spécifications fonctionnelles :
        Cadre juridique et orientations organisationnelles : sfe_cadre_juridique.html
        Organisation du contexte métier : sfe_organisation_contexte_metier.html
        Définition des processus collaboratifs : sfe_definition_processus.html
        Modélisation du contenu du DUI : sfe_modelisation_contenu.html
    Contenu du dossier :
        Contexte: contenu_dossier_contexte.html
        Structure générale du document CDA : contenu_dossier_structure_cda.html
        Entête du document CDA : contenu_dossier_entete_cda.html
        Corps du document CDA : contenu_dossier_corps_cda.html
    Description des flux:
        Synthèse des flux: description_flux_synthese.html
        Flux 1 - Ajout d'un document: description_flux_1_ajout_doc.html
        Flux 2 - Ajout d'un lot de documents: description_flux_2_ajout_lot_doc.html
        Flux 3 - Mise à jour d'un document: description_flux_3_maj_doc.html
    Ressources de conformité:
        Ressources CDA: ressources_cda.html
        Ressources FHIR: artifacts.html
    Annexes: 
        Acronymes: acronymes.html
        Documents de référence: documents_reference.html
        Spécifications FHIR : new-tab {{site.data.fhir.path}}index.html
        Site de l'ANS : new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
