# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.tddui
canonical: https://interop.esante.gouv.fr/ig/fhir/tddui # the last part of canonical and id must be the same
name: TDDUI
title: Médicosocial - Transfert de données DUI
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 1.1.0-ballot # shall conforms to Semantic Versioning https://fr.wiktionary.org/wiki/SemVer
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: trial-use
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

dependencies:
    hl7.fhir.fr.core: 2.1.0
    ans.fr.nos: 1.4.0

parameters:
    shownav: 'true'



pages:
    index.md:
        title: Accueil
    sfe.md:
        title : Spécifications fonctionnelles
        sfe_cadre_juridique.md:
            title : Cadre juridique et orientations organisationnelles
        sfe_organisation_contexte_metier.md:
            title : Organisation du contexte métier
        sfe_definition_processus.md:
            title : Définition des processus collaboratifs
        sfe_modelisation_contenu.md :
            title : Modélisation du contenu du DUI    
    contenu_dossier.md: 
        title : Contenu du dossier CDA
        contenu_dossier_contexte.md:
            title : Contexte
        mapping_fonctionnelle_technique.md:
            title : Mapping CDA du modèle de contenu DUI
        contenu_dossier_structure_cda.md:
            title: Structure générale du document CDA
        contenu_dossier_entete_cda.md:
            title: Entête du document CDA
        contenu_dossier_corps_cda.md: 
            title: Corps du document CDA
        terminology_cda.md:
            title : Jeux de Valeurs CDA
        contenu_sejour.md:
            title : Sejour
        contenu_evenement.md:
            title : Evénement
        contenu_couvertures.md:
            title : Couvertures sociales
        contenu_evaluation.md:
            title : Evaluation
        contenu_documents_ajoutes.md:
            title : Documents ajoutés
        contenu_elements_transversaux.md:
            title : Eléments transversaux

            
    description_flux.md:
        title : Description des flux FHIR
        description_flux_synthese.md:
            title: Synthèse des flux
        description_flux_1_ajout_doc.md:
            title: Flux 1 - Ajout d'un document
        description_flux_2_ajout_lot_doc.md:
            title: Flux 2 - Ajout d'un lot de documents
        description_flux_3_maj_doc.md:
            title: Flux 3 - Mise à jour d'un document
    ressources_conformite.md:
        title : Ressources de conformité
        ressources_cda.md:
            title: Ressources CDA
        artifacts.html:
            title: Ressources FHIR
    tests.md:
        title: Solutions de tests
    annexes.md:
        title: Annexes
        annexes_documents_reference.md:
            title: Documents de référence
        annexes_nomenclatures.md:
            title: Nomenclatures de référence
        annexes_acronymes.md:
            title: Acronymes
    autres_ressources.md:
        title: Autres ressources
        securite.md:
            title: Sécurité
        downloads.md:
            title: Téléchargements et usages
        specs_fhir.md:
            title: Spécifications FHIR
        specs_cda.md:
            title : Spécifications CDA
        site_ans.md:
            title: Site de l'ANS
        documentation.md:
            title: Documentation


menu:
    Accueil : index.html
    Spécifications fonctionnelles :
        Cadre juridique et orientations organisationnelles : sfe_cadre_juridique.html
        Organisation du contexte métier : sfe_organisation_contexte_metier.html
        Définition des processus collaboratifs : sfe_definition_processus.html
        Modélisation du contenu du DUI : sfe_modelisation_contenu.html    
    Contenu du dossier CDA :
        Contexte: contenu_dossier_contexte.html
        Mapping CDA du modèle de contenu DUI : mapping_fonctionnelle_technique.html
        Structure générale du document CDA : contenu_dossier_structure_cda.html
        Entête du document CDA : contenu_dossier_entete_cda.html
        Corps du document CDA : contenu_dossier_corps_cda.html
        Jeux de valeurs CDA : terminology_cda.html
    Description des flux FHIR:
        Synthèse des flux: description_flux_synthese.html
        Flux 1 - Ajout d'un document: description_flux_1_ajout_doc.html
        Flux 2 - Ajout d'un lot de documents: description_flux_2_ajout_lot_doc.html
        Flux 3 - Mise à jour d'un document: description_flux_3_maj_doc.html
    Ressources de conformité:
        Ressources CDA: ressources_cda.html
        Ressources FHIR: artifacts.html
    Tests: tests.html
    Annexes: 
        Documents de référence: annexes_documents_reference.html
        Nomenclatures de référence : annexes_nomenclatures.html
        Acronymes: annexes_acronymes.html
    Autres ressources:
        Sécurité: securite.html
        Téléchargements et usage: downloads.html
        Spécifications FHIR: new-tab {{site.data.fhir.path}}index.html
        Spécifications CDA: new-tab https://hl7.org/cda/stds/core/
        Site de l'ANS: new-tab https://esante.gouv.fr/
        Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
